plugins {
    alias(libs.plugins.agp.lib)
}

val minAPatchVersion: Int by rootProject.extra
val minKsuVersion: Int by rootProject.extra
val maxKsuVersion: Int by rootProject.extra
val minMagiskVersion: Int by rootProject.extra
val verCode: Int by rootProject.extra
val verName: String by rootProject.extra
val commitHash: String by rootProject.extra

android {
    namespace = "app.zygiskd"
    compileSdk = 34
    defaultConfig { minSdk = 23 }
    buildFeatures { buildConfig = false }
    androidResources.enable = false
}

val ndkDirProvider = androidComponents.sdkComponents.ndkDirectory

val abiToTriple = mapOf(
    "arm64-v8a" to "aarch64-linux-android",
    "armeabi-v7a" to "armv7-linux-androideabi",
    "x86" to "i686-linux-android",
    "x86_64" to "x86_64-linux-android"
)

val tripleToClangPrefix = mapOf(
    "aarch64-linux-android" to "aarch64-linux-android",
    "armv7-linux-androideabi" to "armv7a-linux-androideabi",
    "i686-linux-android" to "i686-linux-android",
    "x86_64-linux-android" to "x86_64-linux-android"
)

val generateCargoConfig = tasks.register("generateCargoConfig") {
    doLast {
        val ndkFile = ndkDirProvider.get().asFile
        val prebuiltDir = File(ndkFile, "toolchains/llvm/prebuilt").listFiles()?.firstOrNull()
            ?: error("The LLVM directory was not found in the NDK")

        val isWin = prebuiltDir.name.contains("windows")
        val clangExt = if (isWin) ".cmd" else ""
        val exeExt = if (isWin) ".exe" else ""
        val binDir = File(prebuiltDir, "bin")
        val llvmAr = File(binDir, "llvm-ar$exeExt").absolutePath.replace("\\", "/")

        val cargoDir = file(".cargo")
        cargoDir.mkdirs()

        var toml = """
            # Auto-generated by Gradle. Do not edit.
            [env]
            ANDROID_NDK_HOME = "${ndkFile.absolutePath.replace("\\", "/")}"
            MIN_APATCH_VERSION = "$minAPatchVersion"
            MIN_KSU_VERSION = "$minKsuVersion"
            MAX_KSU_VERSION = "$maxKsuVersion"
            MIN_MAGISK_VERSION = "$minMagiskVersion"
            ZKSU_VERSION = "$verName-$verCode-$commitHash"
        """.trimIndent()

        abiToTriple.values.forEach { triple ->
            val clangPrefix = tripleToClangPrefix[triple]!!
            val clangPath = File(binDir, "${clangPrefix}23-clang$clangExt").absolutePath.replace("\\", "/")
            toml += """
                
                
                [target.$triple]
                linker = "$clangPath"
                ar = "$llvmAr"
            """.trimIndent()
        }

        File(cargoDir, "config.toml").writeText(toml)
    }
}

listOf("Debug", "Release").forEach { variantCap ->
    val profileName = variantCap.lowercase()
    val isRelease = profileName == "release"

    tasks.register("buildAndStrip$variantCap") {
        dependsOn(generateCargoConfig)
        doLast {
            val ndkFile = ndkDirProvider.get().asFile
            val prebuilt = File(ndkFile, "toolchains/llvm/prebuilt").listFiles()?.firstOrNull()!!
            val binDir = File(prebuilt, "bin")
            val exeExt = if (prebuilt.name.contains("windows")) ".exe" else ""
            val strip = File(binDir, "llvm-strip$exeExt")
            val objcopy = File(binDir, "llvm-objcopy$exeExt")
            val outJniDir = layout.buildDirectory.dir("intermediates/rust/$profileName/jniLibs").get().asFile
            val symbolDir = layout.buildDirectory.dir("symbols/$profileName").get().asFile
            abiToTriple.forEach { (abi, triple) ->
                val customTargetDir = layout.buildDirectory.dir("rust/target").get().asFile
                val cargoArgs = mutableListOf(
                    "cargo", "build", 
                    "--target", triple,
                    "--target-dir", customTargetDir.absolutePath
                )

                if (isRelease) { cargoArgs.add("--release") }
                println(">>> Compiling zygiskd binary for $abi...")
                val execResult = providers.exec {
                    workingDir = file(".")
                    commandLine(cargoArgs)
                }.result.get()

                if (execResult.exitValue != 0) {
                    error("CRITICAL: Compilation failed for $abi")
                }

                val executable = File(customTargetDir, "$triple/$profileName/zygiskd")
                if (executable.exists()) {
                    val abiDir = File(outJniDir, abi)
                    abiDir.mkdirs()
                    val targetExe = File(abiDir, "zygiskd")
                    executable.copyTo(targetExe, overwrite = true)
                    val symbolPath = File(symbolDir, "$abi/zygiskd.debug")
                    symbolPath.parentFile.mkdirs()

                    providers.exec { workingDir = abiDir; commandLine(objcopy.absolutePath, "--only-keep-debug", "zygiskd", symbolPath.absolutePath) }.result.get()
                    providers.exec { workingDir = abiDir; commandLine(strip.absolutePath, "--strip-all", "zygiskd") }.result.get()
                    providers.exec { workingDir = abiDir; commandLine(objcopy.absolutePath, "--add-gnu-debuglink", symbolPath.absolutePath, "zygiskd") }.result.get()
                } else {
                    error("CRITICAL ALERT! Binary not found in ${executable.absolutePath}")
                }
            }
        }
    }
}
